services:
  - type: web
    name: fuel-delivery-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: cd dist && NODE_ENV=production node server.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DB_HOST
        value: dpg-cunj0p23esus73ciric0-a
      - key: DB_USER
        value: fuel_delivery_user
      - key: DB_PASSWORD
        value: vcDMwd55ajsFUnZqlPuItAm1k9bIn88N
      - key: DB_NAME
        value: fuel_delivery_db
      - key: PORT
        value: 5432
      - key: ADMIN_EMAIL
        value: eeznetsolutions@gmail.com
    buildFilter:
      paths:
        - package.json
        - src/**
        - public/**
        - database/**

  - type: pserv
    name: mysql
    env: docker
    dockerfilePath: ./Dockerfile.mysql
    plan: starter
    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 10
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: password123
      - key: MYSQL_DATABASE
        value: fuel_delivery_db

  # Frontend service
  - type: web
    name: fuel-delivery-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://fuel-delivery-backend.onrender.com/api

databases:
  - name: fuel-delivery-db
    plan: starter 