services:
  - type: web
    name: fuel-delivery-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGO_URI
        fromDatabase:
          name: fuel-delivery-db
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: fuel-delivery-db
          property: connectionString
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: fuel-delivery-db
    plan: starter