services:
  - type: web
    name: fueldeliveryapp-1
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: fuel-delivery-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci
    startCommand: node server.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGO_URI
        value: mongodb+srv://eeznetsolutions:Yp3mmebgxnQHA6XG@fueldelapp.iaiqh.mongodb.net/fuelDeliveryApp?retryWrites=true&w=majority
      - key: DATABASE_URL
        value: postgres://fuel_delivery_user:vcDMwd55ajsFUnZqlPuItAm1k9bIn88N@dpg-cunj0p23esus73ciric0-a.oregon-postgres.render.com/fuel_delivery_db
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: fuel-delivery-db
    plan: starter